In [ ]:
# Numpy is used for numerical operations
# Numpy are prefered over lists Because list operation become slow for operation on large scale of numbers

In [1]:
pip install numpy # for installation of numpy

In [2]:
import numpy as np # import numpy package using alias name

In [3]:
arr = np.array([1,2,3]) # Declaration of an array using numpy
print(arr)

[1 2 3]


In [8]:
list_user = list((input("enter the number : "))) # Declaration of numpy
arr_user = np.array(list_user) # Taking the input from the user
print(arr_user)

enter the number : 12345
['1' '2' '3' '4' '5']


In [10]:
print(type(arr_user)) # used to find the datatype of the array
print(arr_user.ndim) # To find the dimension of the array
print(arr_user.shape) # To find the shape of the array

<class 'numpy.ndarray'>
<U1
1
(5,)


In [11]:
arr_ndim = np.array([[1,2,3],[4,5,6]]) # Declartion of 2D array
print(arr_ndim)

[[1 2 3]
 [4 5 6]]


In [13]:
arr_1 = np.ones((2,3)) # Declartion of an array of dimension (2,3) with each element "1"
print(arr_1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
arr_1 = np.zeros((2,3)) # Declartion of an array of dimension (2,3) with each element "0"
print(arr_1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
arr_unity = np.eye(3) # Declartion of unit matrix of dimension 3*3
print(arr_unity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
arr_loop = np.arange(0,10,2)
print(arr_loop)

[0 2 4 6 8]


In [22]:
arr_loop_ap = np.linspace(0,10,2)
print(arr_loop_ap)

[ 0. 10.]


In [23]:
arr_loop_gp = np.logspace(0,10,2)
print(arr_loop_gp)

[1.e+00 1.e+10]


In [25]:
arr_random = np.random.rand(2,3) # Declartion of an array of dimension (2,3) with random elements
print(arr_random)

[[0.75390357 0.29440993 0.20328109]
 [0.63736988 0.15355061 0.47451229]]


In [26]:
arr_random = np.random.randn(2,3) # Declartion of an array of dimension (2,3) with random elements which form standard normal deviation mean = 0 and SD = 1
print(arr_random)

[[-1.24349925 -0.58806738  2.43682684]
 [ 0.62112366 -0.1703503  -0.80308126]]


In [29]:
arr_random = np.random.normal(loc = 5,scale = 2,size = (2,3)) # Declartion of an array of dimension (2,3) with random elements which form standard normal deviation mean = 5 and SD = 2
print(arr_random)

[[-0.33748003  4.48180555  6.05212806]
 [ 4.14760979  5.77056836  1.09822367]]
